create_clock -period 10.000 -name APBclk [get_ports APBclk]
set_property PACKAGE_PIN F15 [get_ports APBclk]


set_property PACKAGE_PIN A8 [get_ports {APBraddr[1]}]
set_property PACKAGE_PIN A9 [get_ports {APBraddr[2]}]
set_property PACKAGE_PIN A10 [get_ports {APBraddr[3]}]
set_property PACKAGE_PIN A11 [get_ports {APBraddr[4]}]
set_property PACKAGE_PIN A13 [get_ports {APBraddr[5]}]
set_property PACKAGE_PIN A14 [get_ports {APBraddr[6]}]
set_property PACKAGE_PIN A15 [get_ports {APBraddr[7]}]
set_property PACKAGE_PIN A16 [get_ports {APBraddr[8]}]
set_property PACKAGE_PIN A18 [get_ports {APBraddr[0]}]
set_property PACKAGE_PIN B20 [get_ports {APBwaddr[8]}]
set_property PACKAGE_PIN A20 [get_ports {APBwaddr[7]}]
set_property PACKAGE_PIN A21 [get_ports {APBwaddr[6]}]
set_property PACKAGE_PIN B21 [get_ports {APBwaddr[5]}]
set_property PACKAGE_PIN B22 [get_ports {APBwaddr[4]}]
set_property PACKAGE_PIN A23 [get_ports {APBwaddr[3]}]
set_property PACKAGE_PIN B23 [get_ports {APBwaddr[2]}]
set_property PACKAGE_PIN C20 [get_ports {APBwaddr[1]}]
set_property PACKAGE_PIN D20 [get_ports {APBwaddr[0]}]
set_property PACKAGE_PIN B18 [get_ports {APBwdata[7]}]
set_property PACKAGE_PIN C18 [get_ports {APBwdata[6]}]
set_property PACKAGE_PIN B17 [get_ports {APBwdata[5]}]
set_property PACKAGE_PIN C17 [get_ports {APBwdata[4]}]
set_property PACKAGE_PIN B16 [get_ports {APBwdata[3]}]
set_property PACKAGE_PIN B15 [get_ports {APBwdata[2]}]
set_property PACKAGE_PIN C15 [get_ports {APBwdata[1]}]
set_property PACKAGE_PIN D15 [get_ports {APBwdata[0]}]
set_property PACKAGE_PIN B11 [get_ports {data_out[7]}]
set_property PACKAGE_PIN B10 [get_ports {data_out[6]}]
set_property PACKAGE_PIN B8 [get_ports {data_out[5]}]
set_property PACKAGE_PIN C8 [get_ports {data_out[4]}]
set_property PACKAGE_PIN C9 [get_ports {data_out[3]}]
set_property PACKAGE_PIN C10 [get_ports {data_out[2]}]
set_property PACKAGE_PIN D10 [get_ports {data_out[1]}]
set_property PACKAGE_PIN C12 [get_ports {data_out[0]}]
set_property PACKAGE_PIN F13 [get_ports APBread_write]
set_property PACKAGE_PIN F14 [get_ports APBrst_n]
set_property PACKAGE_PIN E14 [get_ports APBtransfer]
set_property PACKAGE_PIN G17 [get_ports pslverr]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets APBclk_IBUF]

